#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use GoogleDriveList\GoogleDriveListCommand;
use Symfony\Component\Console\Application;

$command = new GoogleDriveListCommand();
$application = new Application();
$application->add($command);
$application->run();
